import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";
import AutoLogoutProvider from "@/contexts/AutoLogoutProvider";
import {UserProvider} from "@/contexts/UserContext"; // 로그인 상태 contexts

const pacifico = Pacifico({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
    variable: "--font-pacifico",
});

export const metadata: Metadata = {
    title: "TOOK TAC",
    description: "Generated by Readdy",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning={true}>
            <body className={`${pacifico.variable} antialiased`} style={{ fontFamily: "Apple SD Gothic Neo" }}>
                <AutoLogoutProvider>
                    <AuthProvider>
                        <UserProvider>
                            <Header />              {/* 모든 페이지에 공통으로 고정 */}
                            <main>{children}</main> {/* 본문만 페이지 전환 시 변경 */}
                        </UserProvider>
                    </AuthProvider>
                </AutoLogoutProvider>
            </body>
        </html>
    );
}
