"""baseline: full schema

Revision ID: 07b67346fb67
Revises: 
Create Date: 2026-07-02 12:30:55.077864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b67346fb67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('desired_job', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('interview_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    op.create_table('final_report_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('rank_value', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('grade_message', sa.Text(), nullable=True),
    sa.Column('personalized_advice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=True),
    sa.Column('knowledge_score', sa.Float(), nullable=True),
    sa.Column('final_text_score', sa.Integer(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('final_feedback', sa.Text(), nullable=True),
    sa.Column('speed_score', sa.Integer(), nullable=True),
    sa.Column('filler_score', sa.Integer(), nullable=True),
    sa.Column('pitch_score', sa.Integer(), nullable=True),
    sa.Column('final_speech_score', sa.Integer(), nullable=True),
    sa.Column('speed_label', sa.String(length=20), nullable=True),
    sa.Column('fluency_label', sa.String(length=20), nullable=True),
    sa.Column('tone_label', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_area_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['final_report_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_improvement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['final_report_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_question_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(length=200), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['final_report_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_strength',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['final_report_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_evaluation_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('gaze_score', sa.Integer(), nullable=True),
    sa.Column('shoulder_warning', sa.Integer(), nullable=True),
    sa.Column('hand_warning', sa.Integer(), nullable=True),
    sa.Column('posture_score', sa.Integer(), nullable=True),
    sa.Column('final_video_score', sa.Integer(), nullable=True),
    sa.Column('positive_rate', sa.Integer(), nullable=True),
    sa.Column('neutral_rate', sa.Integer(), nullable=True),
    sa.Column('negative_rate', sa.Integer(), nullable=True),
    sa.Column('tense_rate', sa.Integer(), nullable=True),
    sa.Column('emotion_best', sa.String(length=20), nullable=True),
    sa.Column('emotion_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_evaluation_result')
    op.drop_table('report_strength')
    op.drop_table('report_question_score')
    op.drop_table('report_improvement')
    op.drop_table('report_area_score')
    op.drop_table('interview_answer')
    op.drop_table('evaluation_result')
    op.drop_table('interview_question')
    op.drop_table('final_report_summary')
    op.drop_index(op.f('ix_resume_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_table('interview_session')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
